# Generated by Django 5.0.1 on 2024-01-31 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(blank=True, max_length=255)),
                ('tearsq1', models.CharField(blank=True, max_length=800, null=True)),
                ('tearsq2', models.CharField(blank=True, max_length=800, null=True)),
                ('tearsq3', models.CharField(blank=True, max_length=800, null=True)),
                ('tearsq4', models.CharField(blank=True, max_length=800, null=True)),
                ('tearsq5', models.CharField(blank=True, max_length=800, null=True)),
                ('tearsq6', models.CharField(blank=True, max_length=800, null=True)),
                ('partyq1', models.CharField(blank=True, max_length=800, null=True)),
                ('partyq2', models.CharField(blank=True, max_length=800, null=True)),
                ('partyq3', models.CharField(blank=True, max_length=800, null=True)),
                ('partyq4', models.CharField(blank=True, max_length=800, null=True)),
                ('gamingq1', models.CharField(blank=True, max_length=800, null=True)),
                ('gamingq2', models.CharField(blank=True, max_length=800, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
