# Generated by Django 5.0.1 on 2024-01-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_account', '0004_userprofile_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='categories',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=17),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='categories',
            field=models.ManyToManyField(to='new_account.category'),
        ),
    ]
