# Generated by Django 4.2.9 on 2024-01-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_account', '0007_remove_userprofile_categories_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tearsq1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
