# Generated by Django 4.2.9 on 2024-01-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_account', '0010_alter_userprofile_partyq1_alter_userprofile_partyq2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='partyq1',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='partyq2',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='partyq3',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='partyq4',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='partyq5',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='partyq6',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tearsq1',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tearsq2',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tearsq3',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tearsq4',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tearsq5',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tearsq6',
            field=models.CharField(max_length=800),
        ),
    ]
