# Generated by Django 5.0.1 on 2024-01-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_account', '0012_remove_userprofile_partyq5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date',
        ),
    ]
